# Generated by Django 3.2.12 on 2025-06-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Naipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome do músico')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('data_ingresso', models.DateField(verbose_name='data de ingresso')),
                ('voz', models.CharField(choices=[('1a', 'Primeira Voz'), ('2a', 'Segunda Voz'), ('3a', 'Terceira Voz')], max_length=2, verbose_name='voz do instrumento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.instrumento', verbose_name='instrumento do músico')),
                ('naipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.naipe')),
            ],
        ),
    ]
