# Generated by Django 5.2 on 2025-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/musicos'),
        ),
    ]
