# Generated by Django 5.2 on 2025-06-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_musico_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('PRES', 'Presidente'), ('VP', 'Vice-presidente'), ('TES', 'Tesoureiro'), ('VT', 'Vice-tesoureiro'), ('SEC', 'Secretário'), ('2SEC', 'Segundo secretário')], max_length=4)),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
